CH = {}

CH.BlacklistAcePermsName = "CH."
CH.BlacklistBypassCommand = "bypassblacklist"


-- language
CH.BlacklistNoPerms = "You dont have the right permissions to use this command."

CH.BlacklistWeapons = {
    "WEAPON_MINIGUN",
	"WEAPON_EMPLAUNCHER",
	"WEAPON_RAYMINIGUN",
	"WEAPON_COMPACTLAUNCHER",
	"WEAPON_HOMINGLAUNCHER",
	"WEAPON_RAILGUN",
	"WEAPON_FIREWORK",
	"WEAPON_GRENADELAUNCHER_SMOKE",
	"WEAPON_GRENADELAUNCHER",
	"WEAPON_RPG",
	"WEAPON_GRENADE",
	"WEAPON_BZGAS",
	"WEAPON_MOLOTOV",
	"WEAPON_STICKYBOMB",
	"WEAPON_PROXMINE",
	"WEAPON_PIPEBOMB",
	"WEAPON_SMOKEGRENADE",
	"WEAPON_RAYCARBINE",
	"WEAPON_RAYPISTOL",
	"WEAPON_FLAREGUN",
	"WEAPON_FLARE",
	"WEAPON_SNIPERRIFLE",
	"WEAPON_HEAVYSNIPER",
	"WEAPON_HEAVYSNIPER_MK2",
	"WEAPON_MARKSMANRIFLE",
	"WEAPON_MARKSMANRIFLE_MK2"
}

CH.BlacklistVehicles = {
    "lazer",
    "rmode63s"
}